Document: fsvalue
Title: Debian fsvalue Manual
Author: <insert document author here>
Abstract: This manual describes what fsvalue is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fsvalue/fsvalue.sgml.gz

Format: postscript
Files: /usr/share/doc/fsvalue/fsvalue.ps.gz

Format: text
Files: /usr/share/doc/fsvalue/fsvalue.text.gz

Format: HTML
Index: /usr/share/doc/fsvalue/html/index.html
Files: /usr/share/doc/fsvalue/html/*.html
