#!/usr/bin/make

#
#  Implantation standard dans /usr/local
#

bindir=			$(DESTDIR)/usr/local/bin
sbindir=		$(DESTDIR)/usr/local/sbin
etcdir=			$(DESTDIR)/usr/local/etc
libdir=			$(DESTDIR)/usr/local/lib
libdir=			$(DESTDIR)/usr/local/include
mandir=			$(DESTDIR)/usr/local/man
docdir=			$(DESTDIR)/usr/local/share/doc
sharedir=		$(DESTDIR)/usr/local/share
perllibdir=		$(DESTDIR)/usr/local/lib/perl5/site_perl
vardir=			$(DESTDIR)/usr/local/var
srvdir=			$(DESTDIR)/usr/local/srv
